### ISSUE TITLE
Support alternative faculty titles

### ISSUE THREAD

**Issue by gondree** [nps-tug/nps-thesis-template#110]
It seems that TPO supports some optional alternatives to faculty titles on certain pages. Such as

- (on the cover) "John Doe"
- (on the signature page) "John Doe, PhD" and sometimes even "Dr. John Doe"

If students want to do these, it might be nice to support macros like:
- \thesisadvisor[John Doe, PhD]{John Doe}
- \secondreader[y]{x}
- \thesisadvisortwo[y]{x}
- \thesisadvisorone[y]{x}
- \departmentchair[y]{x}
- \departmentchairtwo[y]{x}

We need to get official guidance on this, however. Have only heard about these variants anecdotally.

**Comment by janicelong** [comment]
Here is Thesis Processing's guidance:

No ranks or titles whatsoever are allowed on the cover page or the 298.

However, ranks or titles are okay on the title page (page iii), except for job titles like "professor" or common honorifics like "Mr." or "Mrs." 

On the title page, we accept a rank or title before, or after, the name: "Dr. X" or "X, PhD"--just use the same format consistently for all names so affected (and don't mix "Dr." and "PhD" on the same title page).

Example acceptable rank formats:
Joe Smith, LCDR, USN, Ret.
CPT Joe Smith
Capt Joe Smith, USMC
Captain Joe Smith, U.S. Marine Corps

Again, for multiple military advisors, be consistent in format--for example, if you include the service for one advisor, include it for any other military advisor/reader/chair.
