### ISSUE TITLE
Try to support as many TPO macro functions as possible, as the default template behavior

### ISSUE THREAD

**Issue by gondree** [nps-tug/nps-thesis-template#116]
Attached is the word macro TPO uses to check for common errors. We should double-check that all default behavior in the template complies with this, or helps enforce it.
  http://pastebin.com/D8ySxyyw

**Comment by gondree** [comment]
for example, 
 * do not italicize et al. and e.g. and i.e. by default.
 * force a comma after e.g. (line 338)
 * force a comma after i.e. (line 383)
 * force period after et al. when it doesn't end a sentence (line 480, 411)
 * force period after etc. when it doesn't end a sentence (line 398)

Many of the other issues can be discovered by a grep pattern, except that the TeX markup will complicate the issue.

Does anyone have a suggestion on how to search for issues like "Washington DC" vs "Washington, D.C." using grep w/ TeX?

**Comment by toastertaster** [comment]
I think this will be pretty difficult to do with the TeX in place, but with a tool like [opendetex](https://code.google.com/p/opendetex/) it is possible.  I experimented with taking the detex output, swapping all newlines for space character and then using regex to find sequences.  Something like this can help people realize there may be an issue, but it wouldn't identify where in the source .tex files they need to make changes.  The user would still have to determine where to make the edits.

This concept seems to be related to the textlint project: https://github.com/DamienCassou/textlint
I would wonder if you could re-create the web interface for students to upload their files and get feedback on the writing.  I don't know how easy it is to make new rules for textlint to search, though.
Smalltalk files at this location: http://www.squeaksource.com/textlint/

This service could also be used for general publications, too.

**Comment by gondree** [comment]
Closing this as 'wont fix' because its been too long. Some support for house-style 'common acronyms' (#133) have been incorporated, and some macros that 'do the right thing' are in place. Going beyond this isn't worth it, until we get feedback that these existing features are being well-utilized.
