### ISSUE TITLE
latest acronym package causes breakage

### ISSUE THREAD

**Issue by mnectar** [nps-tug/nps-thesis-template#120]
The latest acronym package (https://www.ctan.org/tex-archive/macros/latex/contrib/acronym) removes the \bflabel definition.  This causes the npsreport.cls to fail when trying to redefine bflabel.  A simple fix is to change \renewcommand to \newcommand, but I'm unsure if there's something more elegant that would support users with old versions of the acronym package.

**Comment by gondree** [comment]
@mnectar Can you confirm this fixes the issue for you? The new version uses the \aclabelfont macro.

I tried to build with old and new acro packages, but its hard to detect all possible package conflicts alone.

**Comment by mnectar** [comment]
@gondree Yes, I confirm that 714e79b48733f61c78cc621e7d212a8e6ddf7abe fixes for me when using the new acro package.
